### ISSUE TITLE
Various Bugs

### ISSUE THREAD

**Issue by Katacka** [vargaspu21/BANG_GameFramework#12]
Upon starting the game, the cards can fail to render. Attempting to click on a cads results in a crash likely due to a null reference exception.

There does not seem to be an enforced limit as to bang cards, and the player's draw appears capped at 4 or 6 randomly.

The indians card fails to be consumed and can be played repeatedly to kill all enemy players

One's character card is not visible

Enemy computer players do not seem to be doing anything

**Comment by hujo22** [comment]
Thank you for the reports! Most of them have been fixed, if not all!
