### ISSUE TITLE
timing/turn

### ISSUE THREAD

**Issue by gannotsk21** [vargaspu21/BANG_GameFramework#17]
Can't tell who's turn it is and it looks like the AI's play SUPER quick.  Add some time so that we can see what's happening on other player's turn. Will the player always be the outlaw? Is there another role we can play as?

**Comment by gannotsk21** [comment]
Also, shouldn't all the bulllets disappear once they're dead?

**Comment by hujo22** [comment]
Now, roles are randomly determined. We have also fixed it so that all of the player's resources disappear when they are dead.
