### ISSUE TITLE
Indian Card Bug

### ISSUE THREAD

**Issue by lafave20** [vargaspu21/BANG_GameFramework#6]
I was the sheriff in this load out of the game. It was my first turn and I tapped the INDIAN card in my hand. Once I tapped on the card it was not taken from my hand and placed next to the deck. Instead the card took away a life point every other player. Since the card was still in my hand I could use it until everyone was dead. 
BANG BANG 💯 🔫

**Comment by hujo22** [comment]
We had accidently overlooked this card in particular! The card would never be discarded, and so it could be played infinitely. We called this the Infinite Indian when we had seen that this ended up happening with the card.

Also, hi Ben 🙏
