### ISSUE TITLE
Game Crashes after player 2 and 3 are killed

### ISSUE THREAD

**Issue by nirajlmali** [vargaspu21/BANG_GameFramework#8]
I had the Outlaw roll and managed to kill player 2 and 3. PLayer 4 was the sheriff and when I tried to shoot him the game crashed; the error specifically said the game framework so it may be an issue with that.

**Comment by hujo22** [comment]
It is most likely an error with checking the victory conditions. We are also aware that the health and the imageviews (bullets) reflecting the health are also quite bugged!
